### ISSUE TITLE
Seeing an error in the sauce gem

### ISSUE THREAD

**Issue by lanceblais** [saucelabs/sauce_ruby#346]
Hello, I am using ruby 2.0.0-p645 and when I run `bundle exec rake sauce:spec` I see the following:

*Note: This happens when I run it in a docker container. Might be related? It otherwise works fine from my Mac running ruby 2.0.0-p247.*

```
  Sauce public job link: 
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `map' for nil:NilClass
     # /vendor/bundle/ruby/2.0.0/gems/sauce-3.5.6/lib/sauce/config.rb:223:in `caps_for_location'
     # /vendor/bundle/ruby/2.0.0/gems/sauce-3.5.6/lib/sauce/rspec/rspec.rb:126:in `block in included'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_exec'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_eval_with_args'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/example.rb:247:in `instance_eval_with_args'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/hooks.rb:93:in `block (2 levels) in run'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/hooks.rb:95:in `call'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/hooks.rb:95:in `run'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/hooks.rb:424:in `run_hook'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/example_group.rb:325:in `run_around_each_hooks'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/example.rb:256:in `with_around_each_hooks'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/example.rb:111:in `run'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/example_group.rb:386:in `block in run_examples'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/example_group.rb:382:in `map'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/example_group.rb:382:in `run_examples'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/example_group.rb:367:in `run'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/command_line.rb:28:in `map'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/command_line.rb:28:in `block in run'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/reporter.rb:34:in `report'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/command_line.rb:25:in `run'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/runner.rb:80:in `run'
     # /vendor/bundle/ruby/2.0.0/gems/rspec-core-2.13.0/lib/rspec/core/runner.rb:17:in `block in autorun'
```
